Repository SE-8-2021/frontend, pull requests merged in 2022-01, with the labels that each got.

#33 Add helper text in add repo dialog
  src/App/component/AddRepositoryDialog.jsx
Labels: enhancement

#29 GitHub metrics on dashboard
  package.json
  pnpm-lock.yaml
  src/App/component/DashBoardComponent/CodeBaseViews.jsx
  src/App/component/DashBoardComponent/CommitsViews.jsx
  src/App/component/DashBoardComponent/IssueViews.jsx
  src/App/component/DashBoardComponent/PullRequestViews.jsx
  src/App/component/DashboardPage.jsx
  src/App/component/SelectProject.jsx
Labels: enhancement

#38 [Fix] error when branchName has '/' and bug of reload button
  src/App/component/ComparisonPage.jsx
Labels: bug

#40 fix: Make different accounts can see different projects
  src/App/component/AddProjectDialog.jsx
  src/App/component/BugsPage.jsx
  src/App/component/CodeBasePage.jsx
  src/App/component/CodeCoveragePage.jsx
  src/App/component/CodeSmellsPage.jsx
  src/App/component/CommitsPage.jsx
  src/App/component/ComparisonPage.jsx
  src/App/component/ContributionPage.jsx
  src/App/component/DashBoardComponent/CodeBaseViews.jsx
  src/App/component/DashBoardComponent/CommitsViews.jsx
  src/App/component/DashBoardComponent/IssueViews.jsx
  src/App/component/DashBoardComponent/PullRequestViews.jsx
  src/App/component/DashboardPage.jsx
  src/App/component/DuplicationsPage.jsx
  src/App/component/IssuesPage.jsx
  src/App/component/Login.jsx
  src/App/component/PullRequestsPage.jsx
  src/App/component/SelectProject.jsx
  src/App/component/Sidebar.jsx
  src/App/component/TrelloBoardPage.jsx
Labels: bug

#41 feat: Add register function
  src/App/component/Login.jsx
Labels: enhancement

#43 Refactor Creating Projects
  src/App/component/AddProjectDialog.jsx
Labels: Refactor

#49 fix: Password validation error
  src/App/component/Login.jsx
Labels: bug

#45 Refactor: Four metric pages of SonarQube
  src/App/component/BugsPage.jsx
  src/App/component/CodeCoveragePage.jsx
  src/App/component/CodeSmellsPage.jsx
  src/App/component/DuplicationsPage.jsx
Labels: Refactor

#47 Re-design UI of SelectProject page
  src/assets/defaultAvatar.png
  src/component/ProjectAvatar.jsx
  src/component/SelectProject.jsx
Labels: UIDesign

#44 Refactor: Files except sonar-related files
  src/assets/images/defaultAvatar.png
  src/component/AddProjectDialog.jsx
  src/component/AddRepositoryDialog.jsx
  src/component/BugsPage.jsx
  src/component/CodeBasePage.jsx
  src/component/CodeCoveragePage.jsx
  src/component/CodeSmellsPage.jsx
  src/component/CommitsPage.jsx
  src/component/ComparisonPage.jsx
  src/component/ContributionPage.jsx
  src/component/DashboardPage.jsx
  src/component/DuplicationsPage.jsx
  src/component/IssuesPage.jsx
  src/component/Login.jsx
  src/component/ProjectAvatar.jsx
  src/component/PullRequestsPage.jsx
  src/component/SelectProject.jsx
  src/component/Sidebar.jsx
  src/component/TrelloBoardPage.jsx
Labels: Refactor
